# Generated by Django 4.1.2 on 2022-10-31 14:52

from django.db import migrations, models
import django_countries.fields
import internationalflavor.vat_number.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20221031_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='addressLine1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientLogo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='client',
            name='province',
        ),
        migrations.RemoveField(
            model_name='client',
            name='taxNumber',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='client',
            name='tva',
            field=internationalflavor.vat_number.models.VATNumberField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Belgian-company', 'Belgian company'), ('private-person-EU', 'private person within the EU'), ('company-EU', 'company within the EU'), ('non-EU-customers', 'non-EU customers')], default='Belgian-company', max_length=45),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(default='', max_length=5, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
