# Generated by Django 4.1.2 on 2022-10-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_client_addressline1_remove_client_clientlogo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='ClientName',
        ),
    ]
