# Generated by Django 4.1.2 on 2022-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_rename_clientname_client_clientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'USD')], default='R', max_length=100),
        ),
    ]
