# Generated by Django 4.1.2 on 2022-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='clientLogo',
            field=models.ImageField(default='default_logo.jpg', upload_to='uploads/company_logos'),
        ),
    ]
